PidFile /var/www/site/dbase/run/apache2.pid
WSGISocketPrefix /var/www/site/dbase/run/run.pubscan
ServerName localhost

<VirtualHost *:80>
    DocumentRoot /var/www/site/web

    <Directory /var/www/site>
        Options Indexes FollowSymLinks
        AllowOverride None
        Require all granted
    </Directory>

    # WSGI application using Python venv
    WSGIDaemonProcess pubscan python-home=/var/www/site/dbase/venv python-path=/var/www/site home=/var/www/site
    WSGIProcessGroup pubscan
    WSGIScriptAlias /gw/ /var/www/site/pubscan/

    <Directory /var/www/site/pubscan>
        <Files index.py>
            Require all granted
        </Files>
    </Directory>

    #RewriteEngine On
    #RewriteCond %{REQUEST_FILENAME} !-f
    #RewriteCond %{REQUEST_FILENAME} !-d
    #RewriteRule ^([^/]+)/?$ /index.html?center=$1 [QSA,L]

    # Logs
    ErrorLog /var/www/site/dbase/logs/error.log
    CustomLog /var/www/site/dbase/logs/access.log combined
   
</VirtualHost>

